spring:
  application:
    name: rupixo
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/rupixoDB}
    username: ${DB_USER:}
    password: ${DB_PASS:}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  api-docs:
    title: Rupixo API Documentation
    description: This is the API documentation for the Rupixo application.
    version: OPENAPI_3_1
    path: /rupixo-api-docs